productsSample = [
    "Bạn có sẵn iPhone mới nhất không?",
    "Giá của Samsung Galaxy S21 là bao nhiêu?",
    "OnePlus 9 Pro có màu xanh không?",
    "Thông số kỹ thuật của Google Pixel 6 là gì?",
    "Huawei P50 Pro có sẵn ở cửa hàng của bạn không?",
    "iPhone 13 có những màu gì?",
    "Có giảm giá nào cho Samsung Galaxy Note 20 không?",
    "Sony Xperia 1 III có sẵn không?",
    "Cửa hàng của bạn có Google Pixel mới nhất không?",
    "Có chương trình khuyến mãi nào cho OnePlus Nord không?",
    "Dung lượng lưu trữ của Samsung Galaxy S21 là bao nhiêu?",
    "iPhone SE 2022 có sẵn không?",
    "Sự khác biệt về giá giữa iPhone 12 và 13 là gì?",
    "Motorola Edge 20 có sẵn không?",
    "Google Pixel 6 Pro có sẵn ở cửa hàng của bạn không?",
    "Bạn có bán Xiaomi Mi 11 không?",
    "Có chương trình ưu đãi nào cho Samsung Galaxy Z Fold 3 không?",
    "Oppo Find X3 Pro có sẵn không?",
    "Các tính năng của iPhone 13 Pro là gì?",
    "LG Wing có sẵn không?",
    "Nokia 8.3 5G có sẵn không?",
    "Asus ROG Phone 5 có sẵn không?",
    "Bạn có Realme GT không?",
    "Vivo X60 Pro có sẵn không?",
    "Bạn có Honor 50 không?",
    "Tuổi thọ pin của Samsung Galaxy A52 là bao nhiêu?",
    "ZTE Axon 30 có sẵn không?",
    "Bạn có BlackBerry KEY2 không?",
    "Kích thước màn hình của iPhone 13 Mini là bao nhiêu?",
    "Bạn có TCL 20 Pro 5G không?",
    "Nokia XR20 có sẵn ở cửa hàng của bạn không?",
    "Giá của Samsung Galaxy S20 FE là bao nhiêu?",
    "Bạn có iPhone 12 Pro Max không?",
    "Redmi Note 10 Pro có sẵn không?",
    "Sự khác biệt giữa iPhone 12 và iPhone 13 là gì?",
    "Bạn có Sony Xperia 5 II không?",
    "Thời gian bảo hành của Samsung Galaxy S21 là bao lâu?",
    "Google Pixel 5a có sẵn không?",
    "Bạn có OnePlus 8T không?",
    "Giá của iPhone 13 Pro Max là bao nhiêu?",
    "Samsung Galaxy Z Flip 3 có sẵn không?",
    "Thông số kỹ thuật của Oppo Reno6 Pro là gì?",
    "Bạn có Vivo V21 không?",
    "Motorola Moto G100 có sẵn không?",
    "Bạn có Huawei Mate 40 Pro không?",
    "Realme 8 Pro có sẵn ở cửa hàng của bạn không?",
    "Asus Zenfone 8 có sẵn không?",
    "LG Velvet có sẵn không?",
    "Dung lượng lưu trữ của iPhone 12 là bao nhiêu?",
    "Bạn có Honor Magic 3 không?",
    "Xiaomi Mi 11 Ultra có sẵn không?"
]


chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?",
    'Tôi cần giúp đỡ',
    'Tôi là Hà, đến từ Hà Nội và hôm nay tôi thấy buồn',
    'Tôi là Mai, đến từ Đà Nẵng và hôm nay tôi thấy háo hức',
    'Tôi là Quân, đến từ Hải Phòng và hôm nay tôi thấy thất vọng',
    'Tôi là Minh, đến từ Hải Phòng và hôm nay tôi thấy buồn',
    'Tôi là Đạt, đến từ TP.HCM và hôm nay tôi thấy háo hức',
    'Tôi là Lan, đến từ Cần Thơ và hôm nay tôi thấy háo hức',
    'Bạn từ đâu đến?',
    'Tôi là Thảo, đến từ TP.HCM và hôm nay tôi thấy lo lắng',
    'Tôi là Hà, đến từ Hà Nội và hôm nay tôi thấy hào hứng',
    'Tôi là Hà, đến từ Hải Phòng và hôm nay tôi thấy thất vọng',
    'Tôi là Quân, đến từ Cần Thơ và hôm nay tôi thấy buồn',
    'Tôi đến đây lần đầu',
    'Tôi là Minh, đến từ Huế và hôm nay tôi thấy thất vọng',
    'Tôi là Huy, đến từ Cần Thơ và hôm nay tôi thấy thất vọng',
    'Tôi cảm thấy thất vọng',
    'Hôm nay em hơi hào hứng',
    'Tôi là Minh, đến từ TP.HCM và hôm nay tôi thấy hào hứng',
    'Tôi là Tú, đến từ TP.HCM và hôm nay tôi thấy hào hứng',
    'Em tên là Hà',
    'Tôi là Minh, đến từ TP.HCM và hôm nay tôi thấy lo lắng',
    'Tôi tên là Lan',
    'Hôm nay tôi thấy lo lắng',
    'Hôm nay tôi thấy buồn',
    'Tôi là Đạt, đến từ Đà Nẵng và hôm nay tôi thấy hào hứng',
    'Tên tôi là Tú',
    'Hôm nay em hơi háo hức',
    'Tôi là Hà, đến từ Đà Nẵng và hôm nay tôi thấy hào hứng',
    'Hôm nay bạn thế nào?',
    'Tôi là Nam, đến từ Huế và hôm nay tôi thấy lo lắng',
    'Tôi cảm thấy lo lắng',
    'Tôi là Tú, đến từ Hải Phòng và hôm nay tôi thấy thất vọng',
    'Hôm nay em hơi buồn',
    'Hi',
    'Tôi là Mai, đến từ Hải Phòng và hôm nay tôi thấy vui',
    'Tên tôi là Hà',
    'Tôi đang tìm điện thoại',
    'Có thể nói chuyện một chút không?',
    'Tôi là Hà, đến từ Cần Thơ và hôm nay tôi thấy hào hứng',
    'Tôi là Huy, đến từ Hải Phòng và hôm nay tôi thấy háo hức',
    'Tôi là Mai, đến từ Đà Nẵng và hôm nay tôi thấy vui',
    'Hôm nay tôi thấy hào hứng',
    'Tôi là Mai, đến từ Cần Thơ và hôm nay tôi thấy mệt',
    'Tôi tên là Tú',
    'Tôi tên là Huy',
    'Tôi là Tú, đến từ Đà Nẵng và hôm nay tôi thấy mệt',
    'Tên tôi là Nam',
    'Hôm nay em hơi vui',
    'Tôi là Nam, đến từ Đà Nẵng và hôm nay tôi thấy vui',
    'Tôi tên là Quân',
    'Tôi là Mai, đến từ TP.HCM và hôm nay tôi thấy vui',
    'Mình là Tú',
    'Tôi tên là Minh',
    'Tôi cảm thấy buồn',
    'Mình là Đạt',
    'Mình là Hà',
    'Xin chào',
    'Bạn rảnh không?',
    'Em tên là Tú',
    'Tôi là Đạt, đến từ TP.HCM và hôm nay tôi thấy buồn',
    'Tôi là Nam, đến từ Cần Thơ và hôm nay tôi thấy mệt',
    'Tôi là Hà, đến từ Hải Phòng và hôm nay tôi thấy buồn',
    'Em tên là Thảo',
    'Hôm nay tôi thấy háo hức',
    'Em tên là Nam',
    'Tôi là Nam, đến từ Hải Phòng và hôm nay tôi thấy mệt',
    'Mình là Huy',
    'Tôi tên là Mai',
    'Tôi là Quân, đến từ Huế và hôm nay tôi thấy lo lắng',
    'Tôi là Nam, đến từ Đà Nẵng và hôm nay tôi thấy mệt',
    'Tôi là Tú, đến từ Huế và hôm nay tôi thấy mệt',
    'Tôi là Hà, đến từ TP.HCM và hôm nay tôi thấy vui',
    'Tôi là Hà, đến từ TP.HCM và hôm nay tôi thấy mệt',
    'Tên tôi là Đạt',
    'Mình là Thảo',
    'Tôi là Hà, đến từ Đà Nẵng và hôm nay tôi thấy háo hức',
    'Hôm nay tôi thấy mệt',
    'Tên tôi là Lan',
    'Mình là Lan',
    'Tôi là Hà, đến từ Hà Nội và hôm nay tôi thấy thất vọng',
    'Rất vui được gặp bạn',
    'Tôi là Đạt, đến từ Hà Nội và hôm nay tôi thấy mệt',
    'Tôi là Thảo, đến từ Huế và hôm nay tôi thấy mệt',
    'Tôi là Huy, đến từ Đà Nẵng và hôm nay tôi thấy mệt',
    'Tôi là Thảo, đến từ Hải Phòng và hôm nay tôi thấy mệt',
    'Em tên là Minh',
    'Hôm nay em hơi thất vọng',
    'Tôi là Mai, đến từ Huế và hôm nay tôi thấy hào hứng',
    'Chào buổi sáng',
    'Tôi là Quân, đến từ Đà Nẵng và hôm nay tôi thấy hào hứng',
    'Tôi cảm thấy háo hức',
    'Chào bạn',
    'Em tên là Huy',
    'Tôi tên là Nam',
    'Tên tôi là Quân',
    'Tôi là Thảo, đến từ Đà Nẵng và hôm nay tôi thấy lo lắng',
    'Tên tôi là Mai',
    'Em tên là Quân',
    'Hôm nay em hơi mệt',
    'Tôi cần thông tin sản phẩm',
    'Tôi là Tú, đến từ Hải Phòng và hôm nay tôi thấy mệt',
    'Mình là Nam',
    'Tôi muốn hỏi vài điều',
    'Tôi là Huy, đến từ Huế và hôm nay tôi thấy buồn',
    'Tôi là Huy, đến từ TP.HCM và hôm nay tôi thấy hào hứng',
    'Tôi cảm thấy mệt',
    'Mình là Quân',
    'Tôi là Hà, đến từ Đà Nẵng và hôm nay tôi thấy lo lắng',
    'Tôi là Minh, đến từ Huế và hôm nay tôi thấy vui',
    'Tên tôi là Huy',
    'Tôi là Mai, đến từ Đà Nẵng và hôm nay tôi thấy lo lắng',
    'Hôm nay em hơi lo lắng',
    'Tôi là Nam, đến từ Huế và hôm nay tôi thấy buồn',
    'Tên tôi là Minh',
    'Tôi là Hà, đến từ Hải Phòng và hôm nay tôi thấy mệt',
    'Em tên là Đạt',
    'Tên tôi là Thảo',
    'Tôi tên là Đạt',
    'Tôi là Nam, đến từ Huế và hôm nay tôi thấy vui',
    'Em tên là Lan',
    'Tôi cảm thấy vui',
    'Tôi tên là Hà',
    'Tôi là Tú, đến từ Cần Thơ và hôm nay tôi thấy vui',
    'Có gì mới không?',
    'Hôm nay tôi thấy thất vọng',
    'Tôi là Hà, đến từ Huế và hôm nay tôi thấy vui',
    'Tôi là Nam, đến từ Hải Phòng và hôm nay tôi thấy lo lắng',
    'Mình là Minh',
    'Bạn có khỏe không?',
    'Tôi đang rảnh',
    'Tôi là Tú, đến từ Hà Nội và hôm nay tôi thấy háo hức',
    'Tôi sống ở Cần Thơ',
    'Tôi tên là Thảo',
    'Em tên là Mai',
    'Hello',
    'Tôi là Huy, đến từ Hải Phòng và hôm nay tôi thấy mệt',
    'Tôi là Nam, đến từ Cần Thơ và hôm nay tôi thấy buồn',
    'Tôi là Nam, đến từ Đà Nẵng và hôm nay tôi thấy buồn',
    'Tôi là Tú, đến từ Đà Nẵng và hôm nay tôi thấy vui',
    'Bạn có thể giúp tôi không?',
    'Mình là Mai',
    'Bạn khỏe không?',
    'Bạn tên là gì?',
    'Tôi là Minh, đến từ Hải Phòng và hôm nay tôi thấy thất vọng',
    'Hôm nay tôi thấy vui',
    'Tôi là Tú, đến từ Hà Nội và hôm nay tôi thấy buồn',
    'Tôi là Lan, đến từ Huế và hôm nay tôi thấy lo lắng',
    'Tôi là khách hàng cũ',
    'Tôi cảm thấy hào hứng',
    'Tôi là Đạt, đến từ Hải Phòng và hôm nay tôi thấy hào hứng'
]